### ISSUE TITLE
[BUG] Jitsi Logs Visible to Client

### ISSUE THREAD

**Issue by samad-yar-khan** [RocketChat/RC4Community#131]
Description : 

The Jisti logs are visible to the client

https://user-images.githubusercontent.com/70485812/161855655-84ff7566-5670-4c5a-9e1f-cb9ed7c36873.mp4

Expected Behavior :

Hide Jitsi Logs from Client

**Comment by Dnouv** [comment]
@Sing-Li, could you please close this issue? I don't think this is valid anymore. Thank you!

**Comment by samad-yar-khan** [comment]
@Dnouv Closed :)
