### ISSUE TITLE
[FEATURE] Proposal for Handling all REST api services with axios instance by seperating into modules

### ISSUE THREAD

**Issue by Abusayid693** [RocketChat/RC4Community#160]
Currently the client app uses both **axios and fetch api** spread across many places. It will better to adapt one single solution using axios instance for different services and separating methods into separate modules for **application scalability**. 

Since the application is in early development stage I believe it will be easier to adapt these changes.

Ex :

https://github.com/RocketChat/RC4Community/blob/d5b01dda616313440a287c13a0031cef86890a25/app/lib/api.js#L10

https://github.com/RocketChat/RC4Community/blob/d5b01dda616313440a287c13a0031cef86890a25/app/lib/geoAPI.js#L6

**Solution I propose**

1. Axios instance for Strapi (example)
```js
class Strapi extends Base {
    constructor() {
        this._axios = this.initialise();
    }
   .....
   .....
    handleError = (error) => {
        return Promise.reject(error);
    };
}
```
2. Separate module for endpoint 

```js
export const GITHUB_REPO = '/github-repositories';
export const USERS = "/users"
```

3. API

```js
const _strapi= new Strapi({...);
export const githubRepositories = (body) => _strapi.get(GITHUB_REPO, body);
```

@Sing-Li @debdutdeb any thought on this

**Comment by Sing-Li** [comment]
Interesting idea.   Any reason why you would choose axios over fetch ?

**Comment by Abusayid693** [comment]
One major reason would be because of **compatibility** as it has wide browser support whereas Fetch only supports Chrome 42+, Firefox 39+, Edge 14+, and Safari 10.3+.

Since we are already using **Axios** in lot of places we can stick to it, So when application scales it would provide better developer experience of using one single solution instead of multiple and would be easier to adapt changes.

**Comment by Sing-Li** [comment]
Closing.
