### ISSUE TITLE
[ADD] styles for nft avatar 

### ISSUE THREAD

**Issue by irffanasiff** [RocketChat/RC4Community#164]
This commit adds nft avatar styles to the navbar
- Replace the image url to use it 
- To switch between normal avatar and nft avatar set the ```pfpIsNFT``` variable true or false respectively

**Comment by omkarg01** [comment]
https://github.com/RocketChat/RC4Community/blob/13b5926cfb2029af283bf95bc6995f41fa1ffd73/app/components/auth/rocketchat/ui/RocketChatAuthMenuButton.js#L35-L41

By what, image URL needs to be replaced with?
@demonicirfan may I get help with that.

**Comment by TusharMinche** [comment]
I want to work on this issue. Can you assign me this issue?

**Comment by Dnouv** [comment]
Hey @TusharMinche 
Thanks for your interest. Sorry, but this is already done in #193. However, please feel free to try out the other open issues.

**Comment by SarthakSanjay** [comment]
if this issue is solved please close this issue

**Comment by Sing-Li** [comment]
Done in #193
