### ISSUE TITLE
Tons of linting error in `app` directory

### ISSUE THREAD

**Issue by sidmohanty11** [RocketChat/RC4Community#175]
These linting errors need to be fixed!

![image](https://user-images.githubusercontent.com/73601258/177206578-ea8a7865-1ec0-4e6d-9806-708e4b443db3.png)

**Comment by msabirz** [comment]
Should I take it up?

**Comment by sidmohanty11** [comment]
@msabirz sure

**Comment by msabirz** [comment]
Pls assign it to me

**Comment by sidmohanty11** [comment]
@msabirz I'm sorry, I am not capable of doing that. @debdutdeb @Sing-Li can you help?

**Comment by msabirz** [comment]
Ok pls do the needful

**Comment by msabirz** [comment]
I am taking this

**Comment by debdutdeb** [comment]
Alright @msabirz pls communicate any concerns or questions on our contributors channel. This is a very crucial task, I was going to take it on, thanks for volunteering.

**Comment by msabirz** [comment]
sure @debdutdeb

**Comment by sidmohanty11** [comment]
@msabirz FYI, this is our contributors channel -> https://open.rocket.chat/channel/contributors

**Comment by msabirz** [comment]
Thanks

**Comment by Sing-Li** [comment]
@Palanikannan1437   seems  @msabirz has dropped the ball.    Do you think you can take this (should be straightforward and simple) task on?

**Comment by Sing-Li** [comment]
Basically  `npm run lint` should be *clean*.   under both `app` and `cms` - thanks.

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437   seems  @msabirz has dropped the ball.    Do you think you can take this (should be straightforward and simple) task on? 

Ohh yeah sure! I'll do this before #184 then

**Comment by Sing-Li** [comment]
sure :pray:   #184  can take a while.  This one doesn't require a fast  Internet at all   🙂   🙏

**Comment by Palanikannan1437** [comment]
Sure thing! 

Yup...ouch the internet thing still hurts🙃

Could you please assign it to me @Sing-Li
