### ISSUE TITLE
[TODO]  Update gitpod Yaml

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#186]
With the new all-in-one script from @Dnouv  -  the gitpod deployment is badly outdated and no longer works.

Need to get it updated to support volta based nodeJS/npm version declaration as well as flauna as superprofile in a docker container.

**Comment by Palanikannan1437** [comment]
Hey @Sing-Li , I'd like to look into this.. could you please assign me this?

**Comment by Sing-Li** [comment]
Thanks again @Palanikannan1437      This one is long overdue'd and will benefit almost all new explorers of our codebase  (Gitpod makes it *so easy* and non-committal )   🙏

**Comment by Sing-Li** [comment]
Note that you'll likely want to leverage `prepared docker images` in the workflow to enhance the developer experience.

**Comment by Palanikannan1437** [comment]
> Thanks again @Palanikannan1437 This one is long overdue'd and will benefit almost all new explorers of our codebase (Gitpod makes it _so easy_ and non-committal ) 🙏

Thanks a ton for assigning and guiding me constantly @Sing-Li, I've been going through the gitpod documentation and all existing scripts to get a better understanding!

**Comment by Sing-Li** [comment]
> Are you talking about something else in context of gitpod here?😅

Exactly 🙂 

Ideally, the Gitpod user should be able to just paste in  our repository URL, then ....

1. bam boom boom kapow !!
2. a VSCode windows pops up, a web browser with the site pops up,  with all our servers running on Gitpod, and they can modif y the code immediately

That'll be the *dream* and *ideal* developer experience.

**Comment by Palanikannan1437** [comment]
> > Are you talking about something else in context of gitpod here?😅
> 
> Exactly 🙂 
> 
> Ideally, the Gitpod user should be able to just paste in  our repository URL, then ....
> 
> 1. bam boom boom kapow !!
> 2. a VSCode window pops up, a web browser with the site pops up,  with all our servers running on Gitpod, and they can modify the code immediately
> 
> That'll be the *dream* and *ideal* developer experience.
> 

This definitely is gonna be a super fun thing to work on...I love playing around with automation and scripts to automate my dev workflows!! (with alfred workflows and applescript for now🙃)

https://twitter.com/Palanikannan_M/status/1560511839536001024?t=LZHRKiDDHgTLx7TQVGgYQg&s=19

This is one of the dev scripts I made for opening Rocket.Chat.Electron's dev environment using a single command 😄
