### ISSUE TITLE
[TO DO]  Clean up the components

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#195]
Under the `components` directory, there are currently many components that are taking parameterization directly.  

All components under the `components` directory should be generic and re-usable on multiple `pages`

The components need to be cleaned up badly.

**Comment by Palanikannan1437** [comment]
Hey @Sing-Li, I'd like to clean up and parametrise the components. 

Could you please assign me this issue?

**Comment by Sing-Li** [comment]
Thank you very much @Palanikannan1437 !    Looking forward to the clean-up.
