### ISSUE TITLE
Image slider component broken links

### ISSUE THREAD

**Issue by vasucp1207** [RocketChat/RC4Community#198]
- Arrow link not working.

https://user-images.githubusercontent.com/85363195/201320921-72dc2820-74b9-4e09-999b-d2398381e3f1.mov

**Comment by Palanikannan1437** [comment]
Hey @vasucp1207, good catch there!

Are you willing to submit a PR to fix this issue? 

If so, please let us know and feel free to ping us here...we'd be glad to help you out with your first contribution to RC4Community 😄

**Comment by vasucp1207** [comment]
@Palanikannan1437, Yes I am interested.

**Comment by Palanikannan1437** [comment]
> @Palanikannan1437, Yes I am interested.

@Sing-Li could you please assign this issue to @vasucp1207! Thank you!

**Comment by Sing-Li** [comment]
Thanks @Palanikannan1437 !        @vasucp1207 , looking forward to your fixes.

**Comment by r3yc0n1c** [comment]
Hi! I'd like to revamp the fixes which'll work with the svg arrows. Could you please assign it to me?

**Comment by Palanikannan1437** [comment]
> Hi! I'd like to revamp the fixes which'll work with the svg arrows. Could you please assign it to me?

Hey @Sing-Li , @r3yc0n1c has proposed a solution for this issue as well whilst keeping our design at place💫, could you please assign it to him?

**Comment by vasucp1207** [comment]
@Palanikannan1437, I'm working on this as of now if I will not able to do it then I will tell you.

**Comment by Sing-Li** [comment]
Thanks @r3yc0n1c for the offer 🙏    Let's see if @vasucp1207 can complete the fix as per requirement this week (7 days since issue open).
