### ISSUE TITLE
[FIX] Log In button not working

### ISSUE THREAD

**Issue by muneeb-i-khan** [RocketChat/RC4Community#206]

**Comment by Palanikannan1437** [comment]
@muneeb-i-khan Please give us more context on what exactly isn't working for you in detail so that we could help you debugging it!!

**Comment by muneeb-i-khan** [comment]
After I click on the profile button at top on extreme right. A login button appears and when I click that, nothing seems to happen.

**Comment by Palanikannan1437** [comment]
Hey @muneeb-i-khan!!, I believe you haven't setup these environment variables in your `.env` file,

```dosini
NEXT_PUBLIC_GOOGLE_CLIENT_ID="your google client id"
NEXT_PUBLIC_RC_URL="your url of the RC instance"
```

You could refer to [this doc](https://github.com/RocketChat/RC4Community/blob/5382a5bc3811f10ab797897e4cff7b55a44adcf9/app/components/auth/rc-auth-google/Readme.md) for further clarity, thank you so much for letting us know! 🙌

Please let us know if you have any further queries!

**Comment by muneeb-i-khan** [comment]
Thanks for helping out

**Comment by Palanikannan1437** [comment]
If everything works, please consider closing this issue @muneeb-i-khan! 😄

Thank you for bringing this to our notice again...this definitely helped improve our docs a bit more🎉!
