### ISSUE TITLE
TODO:   Fix the Discourse Module

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#21]
Current Discourse module will keep populating the top ranking list to 10s or 100s of entries.

Re-implement the logic to select the TOP N entries - with N anywhere from 3  to 15 ONLY.

Define a "module structure" that makes sense for these sort of "full stack reactjs components", beware it will always be executing on nextJS  (keep to JAMStack ideals).

Keep this work on ONE SINGLE PR.

**Comment by samad-yar-khan** [comment]
@Sing-Li I would like to work on this issue. So we store the top N entries from the request in our CMS, repopulate them at intervals using cron jobs and make the top N entries accessible to the NextJS component depending on the parameters given to component ?

**Comment by RonLek** [comment]
@samad-yar-khan that's correct. If you see the current codebase, we have a cron function [calling](https://github.com/RocketChat/RC4Community/blob/master/cms/config/functions/cron.js#L23) the `fetchTopPosts` function. Instead of storing all possible entries store only the top N within the CMS.

**Comment by samad-yar-khan** [comment]
@RonLek Got it ! I will start working on this.
