### ISSUE TITLE
TODO:  Implement Jitsi  Video Conference component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#28]
Create a reactJS component from the Jitsi web SDK.

This component should enable community members to video conference with one another in:

- 1 to 1 calls
- scheduled meetings
- scheduled virtual events

**Comment by nishant23122000** [comment]
@Sing-Li  Would like to work on that.

**Comment by Dnouv** [comment]
Hello @Sing-Li 
I would like to work on this issue. Hello, @nishant23122000 if you ain't working on this issue please let me know.
Thank you!

**Comment by Sing-Li** [comment]
Done as part of RC4Conferences.
