### ISSUE TITLE
TODO:  Create a Leaderboard Component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#31]
Based this React component's interface on the existing GSoC Leadeboard.

Keep the interface flexible for repurposing as Game players' Leaderboard.

**Comment by samad-yar-khan** [comment]
@Sing-Li  I would like to work on this, can you please assign this to me. 
I had a few questions :

- Should the UI be similar to the hosted leader board component ?
- Where should the component be placed ? Should it be placed under the Events/GSOC section ?

**Comment by Sing-Li** [comment]
1)  yes.  Identical if possible.  
2)  add a NextJS client route there  at  `/gsoc/gsoc2022/leaderbaord`    or similar   

In addition, the component should cater for, independently all of:
*  static generation (data fetch) at site build time
*  dynamic per request update (data fetch)
*  server-side rendering

**Comment by samad-yar-khan** [comment]
@Sing-Li got it ! I will start working on it right away 👍

**Comment by Sing-Li** [comment]
@samad-yar-khan   please start a WIP PR and commit your work frequently.    This will enable us to review it as you code -- so there won't be misunderstanding or time wasted.  Thanks.

**Comment by samad-yar-khan** [comment]
@Sing-Li I will just raise a WIP PR by tonight. I am sorry the work got a bit delayed because I was trying to just go through the  NEXT.JS documentation, as I wasn't fully familiar with all features of the framework. But now I am through with it and it development should be quicker :sweat_smile:

**Comment by Sing-Li** [comment]
@samad-yar-khan  no problem at all.   It is very important to understand why this project is based on NextJS and why NextJS exists at all (what value does it add - why don't we just create React app with standard JS toolchain directly and serve it with Nginx) 👍

**Comment by samad-yar-khan** [comment]
@Sing-Li Yes, read the docs and went through some videos made by the the Vercel team. I understand how NextJS can be useful for multiple reasons, the primary one being able to generate server side rendered pages at build time, leading to better SEO. Can you take a look at the PR. I Think I have added all of the functionality of our original leaderboard.

**Comment by Sing-Li** [comment]
@samad-yar-khan amazing work!   Thank you!    Please see my comments in-line.    I think turning it into a more flexible component will enable our Community Builders to better flexibly design their pages containing the leaderboard.
