### ISSUE TITLE
TODO:  Create a virtual conferencing component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#38]
Creaete a React component for conducting virtual conferences between community members.

Re-use the Jitsi or  Big Blue Button component if it makes sense.

**Comment by Sing-Li** [comment]
This composes a chat component with #56

**Comment by sidmohanty11** [comment]
@Sing-Li I would like to work on this issue

**Comment by Sing-Li** [comment]
RC4Conferences project is a set of such components now.
