### ISSUE TITLE
TODO:  Create an integration surfacing browser supported wallet

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#41]
Create a React component that surfaces the features of browser integrated crypto wallets for community members,   such as via MetaMask extension or via built-in wallet of the Brave browser.

**Comment by Dnouv** [comment]
Hello @Sing-Li, 
I would like to work on this issue. As for the initial start idea, I've planned to integrate the `MetaMask` API in a component. So it will be something like a button `Connect MetaMask` when the user clicks on this button a window will popup for authentication with MetaMask and after the successful authentication, the user data returned from the MetaMask will be shown in a small Modal or a badge component.
, shall we discuss this issue in the same `form` channel? Please let me know. Thank you!
