### ISSUE TITLE
[BUG]: Header logo is not loading

### ISSUE THREAD

**Issue by Himanshu664** [RocketChat/RC4Community#43]
## Description
I found a bug in the header part in https://community.rocket.chat/ , source of img is not valid

![InkedScreenshot 2022-01-20 160643_LI](https://user-images.githubusercontent.com/76220055/150323289-3dcc7911-18bb-49a1-865f-1af12fbeb527.jpg)

**Comment by RonLek** [comment]
@Himanshu664 please feel free to raise a PR.
