### ISSUE TITLE
TODO:  Add a video streaming viewer component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#56]
Like a youtube viewer.   Shows thumbnail of video .   Upon clicking starts to play video.

Enable "standard" playback controls of the underlying libray.

Make sure it can efficiently support multiple instances on one page.

**Comment by Sing-Li** [comment]
First cut is available here  https://github.com/RocketChat/RC4Community/commit/650e4b1c4d1d3271cf9a85695b9f310e5d8c6375

**Comment by pushpanjali-10** [comment]
I want to work on this.

**Comment by Sing-Li** [comment]
Completed as part of RC4Conferences
