### ISSUE TITLE
TODO:  Add a form fill component

### ISSUE THREAD

**Issue by Sing-Li** [RocketChat/RC4Community#57]
Create a component that manages an interactive form to be filled.

Form data should be pushed to our persistence implementation data lake.

An indication if that form has been filled already, should be part of the Superprofile.

Make sure multiple instances on a page is easily handled.

**Comment by Dnouv** [comment]
Hello @Sing-Li 
I am interested in working on this issue; however, I have some questions regarding this issue; if it is ok with you, can we discuss this in more detail in the #general channel? Please let me know then I will ping you.
Thank you!

**Comment by Sing-Li** [comment]
@Dnouv   please feel free to post right here or ping us at this channel  https://open.rocket.chat/channel/form-fill-component-details    Thanks.

**Comment by Sing-Li** [comment]
Completed in RC4Conferences.
