### ISSUE TITLE
[BUG] Unable to load the community logo

### ISSUE THREAD

**Issue by nipunayf** [RocketChat/RC4Community#95]
The community logo in the home page does not appear after loading the page.
<img src="https://user-images.githubusercontent.com/59343084/159180034-d5732cd1-e5a8-48bd-b0ab-5aaf183d150e.png" width="600"/>

The attached URL points to a resource that does not exist. 
<img src="https://user-images.githubusercontent.com/59343084/159180049-5da95d9a-ef0c-4352-8e39-1cdfeae2e7ee.png" width="600"/>

**Browser version:**
Google Chrome - Version 99.0.4844.51 (Official Build) (64-bit)

**Comment by progmatic-99** [comment]
It's visible to me.

![Screenshot 2022-03-24 at 12-06-14 Create Next App](https://user-images.githubusercontent.com/42090582/159856930-0a69f0fd-c821-4309-8482-c5c8286b194b.png)

**Comment by sidmohanty11** [comment]
It's fixed here: https://github.com/RocketChat/RC4Community/pull/46

**Comment by Dnouv** [comment]
@Sing-Li, could you please close this issue? It's fixed. Thanks!
